# This file was generated by GoReleaser. DO NOT EDIT.
cask "govi" do
  app "govi.app"

  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "16c6632e7d1549dd1191ee15f1dd450ea7d3135a2f5b599108fc64512fb3f49b"
      url "https://github.com/andresbott/govi/releases/download/v#{version}/govi_Darwin_arm64.tar.gz",
        verified: "github.com/andresbott/govi/"
    end
  end

  name "govi"
  desc "Minimalistic video player based on mpv"
  homepage "https://github.com/andresbott/govi"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mpv",
    ]

  binary "#{appdir}/govi.app/Contents/MacOS/govi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/govi.app"]
    end
  end

  # No zap stanza required

end
